### ISSUE TITLE
Latest Hyprland Build don't work anymore

### ISSUE THREAD

**Issue by linuxmobile** [Duckonaut/split-monitor-workspaces#28] opened 2023-09-09 01:43 UTC
Hyprland change wlr/workspaces to hyprland/workspaces. Idk if is this but don't work anymore

**Comment by Duckonaut** [comment] 2023-09-13 13:29
This seems unrelated, and after a rebuild the plugin seems to still be working perfectly on my machine as of Hyprland commit 2ad429dfe0687b34c1a4d950e7715f0c8550bed5? If you have any more details, let me know

**Comment by jess-sol** [comment] 2023-10-22 23:03
I was having issues too with the example Nix config in the readme too.
Here's an example flake I was using for testing:
```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    hyprland.url = "github:hyprwm/Hyprland?ref=v0.31.0";
    split-monitor-workspaces = {
      url = "github:Duckonaut/split-monitor-workspaces";
      inputs.hyprland.follows = "hyprland";
    };
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    split-monitor-workspaces,
    ...
  }: let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    homeConfigurations.jessica = home-manager.lib.homeManagerConfiguration {
      pkgs = import nixpkgs {
        inherit system;
        config.allowUnfree = true;
      };

      modules = [{
        wayland.windowManager.hyprland = {
          enable = true;
          plugins = [
            split-monitor-workspaces.packages.${pkgs.system}.split-monitor-workspaces
          ];
        };

        home.username = "jessica";
        home.homeDirectory = "/home/jessica";
        home.stateVersion = "22.11";
      }];
    };
  };
}
```

And `home-manager build --flake .`. Make sure to change the username to your own for testing.

I confirmed it does work on `2ad429dfe0687b34c1a4d950e7715f0c8550bed5`, but not on current main (`98059b52d759965916e0185ca35a01cc20a797b6`). It may be worth adding a `ref=v0.31.0` to the example in the readme so the Hyprland version can be pinned to known good one.

**Comment by zjeffer** [comment] 2024-04-07 21:23
Closing because the original issue seems to be talking about Waybar (where the `hyprland/workspaces` module is now recommended instead of `wlr/workspaces`), not split-monitor-workspaces.

@jess-sol If you still have problems, please open a new issue

**Closed by zjeffer** 2024-04-07 21:23 UTC
