### ISSUE TITLE
Crash on hyprland v0.41.2-39-gbc6b0880, commits: 4925

### ISSUE THREAD

**Issue by jorgemota** [Duckonaut/split-monitor-workspaces#106] opened 2024-07-15 15:29 UTC
*hyprland.log:
cat $XDG_RUNTIME_DIR/hypr/$(ls -t $XDG_RUNTIME_DIR/hypr/ | head -n 2 | tail -n 1)/hyprland.log*
[hypr.log](https://github.com/user-attachments/files/16236560/hypr.log)

*hyprctl systeminfo*:
[systeminfo.txt](https://github.com/user-attachments/files/16236561/systeminfo.txt)

After upgrade of hyprland, I got warnings about split-monitor-workspaces dispatcher, so I ran
```
 hyprpm remove https://github.com/Duckonaut/split-monitor-workspaces -v 
 hyprpm add https://github.com/Duckonaut/split-monitor-workspaces -v 
```
Ask me to update headers *hyprpm update* executed without warnings
I ran again
```hyprpm add https://github.com/Duckonaut/split-monitor-workspaces -v ```

```
hyprpm add https://github.com/Duckonaut/split-monitor-workspaces -v
[v] version returned: Hyprland, built from branch main at commit bc6b0880dda2607a80f000c134f573c970452a0f  (window: override noMaximize if new window takes over fullscreen (6812) (6870)).
Date: Sat Jul 13 12:44:32 2024
Tag: v0.41.2-39-gbc6b0880, commits: 4925

flags: (if any)


[v] parsed commit bc6b0880dda2607a80f000c134f573c970452a0f at branch main on Sat Jul 13 12:44:32 2024, commits 4925
✔ adding a new plugin repository from https://github.com/Duckonaut/split-monitor-workspaces
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] y

 → Cloning https://github.com/Duckonaut/split-monitor-workspaces                                                             
✔ cloned                                                                                                                     
✔ found hyprpm manifest                                                                                                      
✔ parsed manifest, found 1 plugins:                                                                                          
 → split-monitor-workspaces by Duckonaut version                                                                             
 → Manifest has 6 pins, checking                                                                                             
✔ Hyprland headers OK                                                                                                        
 → Building split-monitor-workspaces                                                                                         
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/jorge && PKG_CONFIG_PATH="/home/jorge/.local/share/hyprpm/headersRoot/share/pkgconfig" meson setup build --wipe
The Meson build system
Version: 1.5.0
Source dir: /tmp/hyprpm/jorge
Build dir: /tmp/hyprpm/jorge/build
Build type: native build
Project name: split-monitor-workspaces
Project version: 0.1
C++ compiler for the host machine: c++ (gcc 14.1.1 "c++ (GCC) 14.1.1 20240522")
C++ linker for the host machine: c++ ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -std=c++23: YES 
meson.build:8: WARNING: Consider using the built-in option for language standard version instead of using "-std=c++23".
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency hyprland found: YES 0.41.2
Run-time dependency pixman-1 found: YES 0.43.4
Run-time dependency libdrm found: YES 2.4.122
Build targets in project: 1

Found ninja-1.12.1 at /usr/bin/ninja
                                                
 -> cd /tmp/hyprpm/jorge && PKG_CONFIG_PATH="/home/jorge/.local/share/hyprpm/headersRoot/share/pkgconfig" meson compile -C build
ninja: Entering directory `/tmp/hyprpm/jorge/build'
[1/2] Compiling C++ object libsplit-monitor-workspaces.so.p/src_main.cpp.o
[2/2] Linking target libsplit-monitor-workspaces.so
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /tmp/hyprpm/jorge/build


✔ built split-monitor-workspaces into build/libsplit-monitor-workspaces.so                                                   
✔ all plugins built                                                                                                          
✔ installed repository                                                                                                       
✔ you can now enable the plugin(s) with hyprpm enable
```

after run hyprpm enable Hyprland closes/crashes and SDDM ask me for user / password

I cleaned some files, rebooted, reinstalled hyprland-git on arch with same error, only happens when I ran hyprpm enable with this plugin but I cannot see any error info on hyprland log

I tried to run hyprctl plugin load ~/.local/share/hyprpm/split-monitor-workspaces/split-monitor-workspaces.so 
But gave me an error about not found /library:

``hyprctl plugin load split-monitor-workspaces.so
error in loading plugin, last error: Plugin split-monitor-workspaces.so could not be loaded: split-monitor-workspaces.so: cannot open shared object file: No such file or directory``

I have already deleted folder, rebooted, removed the repository but cannot find a way to get working this plugin again. Someone have an idea what I can check? 

Edit, I ran 
```split-monitor-workspaces.so
ldd split-monitor-workspaces.so
	linux-vdso.so.1 (0x000071223d178000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000071223ce00000)
	libm.so.6 => /usr/lib/libm.so.6 (0x000071223cd15000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000071223d0c9000)
	libc.so.6 => /usr/lib/libc.so.6 (0x000071223cb29000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000071223d17a000)
❯ sudo pacman -F linux-vdso.so.1
```
*last command don't returns anything

I am going to check who can install this library on arch linux.

**Comment by zjeffer** [comment] 2024-07-15 17:03
> I tried to run hyprctl plugin load ~/.local/share/hyprpm/split-monitor-workspaces/split-monitor-workspaces.so
But gave me an error about not found /library:

Is the file actually there?

**Comment by jorgemota** [comment] 2024-07-15 17:05
> > I tried to run hyprctl plugin load ~/.local/share/hyprpm/split-monitor-workspaces/split-monitor-workspaces.so
> > But gave me an error about not found /library:
> 
> Is the file actually there?

Yes, the file exist, check my last update please, there is a reference to linux-vdso.so.1 But I can't find what package can install it.

**Comment by jorgemota** [comment] 2024-07-15 17:51
I think the problem it's in Hyprland and not in split-monitor... 
Enabled plugin 1 by 1 in https://github.com/hyprwm/hyprland-plugins and got same behavior with hyprExpo 

Must be something related, but I can't figure what can be.

**Comment by zjeffer** [comment] 2024-07-15 18:01
Since Hyprland crashes, can you get a backtrace by running it through gdb, and then enabling the plugin? Or at least share the crashreport in ~/.cache/hyprland/

**Comment by zjeffer** [comment] 2024-07-15 18:08
That doesn't show the backtrace, only the hyprland logs. Please share the most recent hyprland crash report in ~/.cache/hyprland/

**Comment by zjeffer** [comment] 2024-07-15 19:42
Shouldn't be necessary. If hyprland crashes, there should be files in ~/.cache/hyprland/.

What's the output of `ls -la ~/.cache/hyprland/`?

**Comment by jorgemota** [comment] 2024-07-15 20:00
no files are there, maybe when I reinstalled hyprland I deleted the folder,

> Shouldn't be necessary. If hyprland crashes, there should be files in ~/.cache/hyprland/.
> 
> What's the output of `ls -la ~/.cache/hyprland/`?

**Comment by zjeffer** [comment] 2024-07-15 20:16
Try to make it crash again, and then see if there is a file there.
I can't really investigate much without that backtrace.

**Comment by jorgemota** [comment] 2024-07-15 20:24
[hyprlandCrashReport25824.txt](https://github.com/user-attachments/files/16239957/hyprlandCrashReport25824.txt)

**Comment by zjeffer** [comment] 2024-07-15 20:32
What is your monitor configuration? Do you have any mirrored monitors?

**Comment by jorgemota** [comment] 2024-07-15 20:33
Hi, I have 3 monitors
None mirrored:

#
monitor=DVI-D-1,2560x1440,1920x0,1
monitor=HDMI-A-3,1920x1080,0x410,1
monitor=HDMI-A-4,2560x1080,4480x415,1

**Comment by zjeffer** [comment] 2024-07-15 20:39
Can you try building this PR: #107, and loading the plugin with `hyprctl plugin load <path-to-so-file>`?

**Comment by jorgemota** [comment] 2024-07-15 20:42
How I can do that ? Can give me a link , I can download the code with git, but I have never used a PR before.

**Comment by zjeffer** [comment] 2024-07-15 20:45
1. `git clone https://github.com/Duckonaut/split-monitor-workspaces`
2. `cd split-monitor-workspaces`
3. `git checkout fix/zjeffer/crash-106`
4. `meson setup build --wipe && ninja -C build`. The so file should now be in `<repo-folder>/build/libsplit-monitor-workspaces.so`. 
6. Load it with hyprctl: `hyprctl plugin load $PWD/build/libsplit-monitor-workspaces.so`.

**Comment by jorgemota** [comment] 2024-07-15 20:49
[hyprlandCrashReport319415.txt](https://github.com/user-attachments/files/16240147/hyprlandCrashReport319415.txt)

**Comment by zjeffer** [comment] 2024-07-15 20:58
I pushed another commit to that branch.

1. `git pull`
2. `meson setup build --wipe && ninja -C build`
3. `hyprctl plugin load $PWD/build/libsplit-monitor-workspaces.so`

**Comment by jorgemota** [comment] 2024-07-16 00:50
> I pushed another commit to that branch.
> 
> 1. `git pull`
> 2. `meson setup build --wipe && ninja -C build`
> 3. `hyprctl plugin load $PWD/build/libsplit-monitor-workspaces.so`

Hi, I have tested a lot 
I rebuild and ran hyprctl plugin load $PWD/build/libsplit-monitor-workspaces.so
Got a notification about the plugin  loaded
Hyprland dont crash but, I cannot move to another workspace  

with this keybind
bind = $mainMod SHIFT, 2, split-movetoworkspacesilent, 2
I move a window to workspace 2 in current monitor, but now when  I press the key move window to second monitor 
same for shit 1, and shift 3

If I configure shift 4 split-movetoworkspacesilent 4 (I only have 3 monitors) the plugin works nice and I can move between workspaces on that monitor sometimes

**Comment by zjeffer** [comment] 2024-07-16 19:17
>  Hyprland dont crash but, I cannot move to another workspace

Can you share the hyprland logs when you try to move to another workspace?

**Comment by jorgemota** [comment] 2024-07-16 20:25
Hi, I currently have tested this

bind = $mainMod SHIFT, 4, split-movetoworkspacesilent, 4 
with 1 to 4, to move to another workspace, but only 4 works, 1..3 move window to monitor 1.2.3

bind = $mainMod, 1, split-workspace, 1 
with this to 1.to 3 this move cursor to respective monitor but no workspace change
![image](https://github.com/user-attachments/assets/51682312-6215-443a-be92-376967d87902)

I tried a lot but don't get any log in .cache/hyprland
![image](https://github.com/user-attachments/assets/d6e95cb1-54d9-467b-ac18-58eef3d3dc30)

**Comment by zjeffer** [comment] 2024-07-16 20:28
> I tried a lot but don't get any log in .cache/hyprland

To be clear:
* The *logs* are in `$XDG_RUNTIME_DIR/hypr/<id>/hyprland.log`
* The *backtraces* (=crash reports) are in `~/.cache/hyprland/`

You should post the logfile `$XDG_RUNTIME_DIR/hypr/<id>/hyprland.log`

**Comment by jorgemota** [comment] 2024-07-16 20:33
> > I tried a lot but don't get any log in .cache/hyprland
> 
> To be clear:
> 
> * The _logs_ are in `$XDG_RUNTIME_DIR/hypr/<id>/hyprland.log`
> * The _backtraces_ (=crash reports) are in `~/.cache/hyprland/`
> 
> You should post the logfile `$XDG_RUNTIME_DIR/hypr/<id>/hyprland.log`
before change debug:disable_logs
[hyprland.log](https://github.com/user-attachments/files/16256335/hyprland.log)

after change debug:disable_logs
[hyprland2.log](https://github.com/user-attachments/files/16256374/hyprland2.log)

**Comment by zjeffer** [comment] 2024-07-16 20:41
Your logs contain this line quite a lot:

```
[WARN] [split-monitor-workspaces] Last monitor does not exist, falling back to cursor's monitor
```

This is really weird and makes me think there's an issue with Hyprland.

---

Are these logs with the latest build of PR 107? I don't see the debug logs I added.

**Comment by zjeffer** [comment] 2024-07-16 20:52
> If I configure shift 4 split-movetoworkspacesilent 4 (I only have 3 monitors) the plugin works nice and I can move between workspaces on that monitor sometimes

What do you mean by this?

This plugin will create `x` workspaces on each monitor, `x` being defined by `count = x` in the split-monitor-workspaces plugin configuration. In your case you set `x` to 4. This means that each monitor will have 4 workspaces assigned to it. If you call `split-movetoworkspacesilent, 4`, this means you will send the currently focused window to the 4th workspace on the current monitor (silently, meaning you don't activate that workspace, you'll stay on the current workspace). 

The `split-workspace x` dispatcher will activate the `x`th workspace on the current monitor. This has nothing to do with the amount of monitors  you have.

**Comment by jorgemota** [comment] 2024-07-16 20:52
the  warning must be when I press win+Shift +4 or win+4 

I have this 
```
 hyprpm list
 → Repository hyprland-plugins:
  │ Plugin borders-plus-plus
  └─ enabled: false
  │ Plugin csgo-vulkan-fix
  └─ enabled: false
  │ Plugin hyprbars
  └─ enabled: false
  │ Plugin hyprexpo
  └─ enabled: false
  │ Plugin hyprtrails
  └─ enabled: false
  │ Plugin hyprwinwrap
  └─ enabled: false
 → Repository split-monitor-workspaces:
  │ Plugin split-monitor-workspaces
  └─ enabled: false
```
and to load the plugin I have a exec-onse =/opt/stuff/loadhypr-plugins
```
/usr/bin/hyprpm update
#/usr/bin/hyprpm enable split-monitor-workspaces
#/usr/bin/hyprpm enable hyprexpo
/usr/bin/hyprctl plugin load /home/jorge/split-monitor/build/libsplit-monitor-workspaces.so
```

running git  remote-v gave me this:
```
❯ cd /home/jorge/split-monitor/build
❯ ls
build.ninja  compile_commands.json  libsplit-monitor-workspaces.so  libsplit-monitor-workspaces.so.p  meson-info  meson-logs  meson-private
❯ git fetch
git%                                                                                                                                                                                                                                                                  ❯ git pull
fAlready up to date.
❯ git remote -v
origin	https://github.com/Duckonaut/split-monitor-workspaces (fetch)
origin	https://github.com/Duckonaut/split-monitor-workspaces (push)
❯ git rev-parse --abbrev-ref HEAD
fix/zjeffer/crash-106
```


I got another crash with this keybinding
bind = $mainMod,o,exec, hyprctl dispatch split-changemonitor +1
bind = $mainMod SHIFT,o,exec, hyprctl dispatch split-changemonitor -1 

[hyprland.log](https://github.com/user-attachments/files/16256476/hyprland.log)
[hyprlandCrashReport1428.txt](https://github.com/user-attachments/files/16256478/hyprlandCrashReport1428.txt)

How I can check if the .so I am executing is the same you need, I ran this again
meson setup build --wipe && ninja -C build

I am going to reboot to test again.

**Comment by jorgemota** [comment] 2024-07-16 20:56
after rebuild do a small test, change to workspace 4, move window to workspace 4, then 1,2,3 and a few tests 

[hyprland.log](https://github.com/user-attachments/files/16256505/hyprland.log)

**Comment by zjeffer** [comment] 2024-07-16 20:58
> after rebuild do a small test, change to workspace 4, move window to workspace 4, then 1,2,3 and a few tests
> 
> [hyprland.log](https://github.com/user-attachments/files/16256505/hyprland.log)

```
[INFO] [split-monitor-workspaces] Notifications are enabled
[INFO] [split-monitor-workspaces] Mapping 4 workspaces to monitors...
[WARN] [split-monitor-workspaces] Monitor is null
[WARN] [split-monitor-workspaces] Monitor is null
[WARN] [split-monitor-workspaces] Monitor is null
```
Something is definitely wrong here: all your monitors are null.

What's the output of `hyprctl monitors -j`

**Comment by jorgemota** [comment] 2024-07-16 20:58
> > If I configure shift 4 split-movetoworkspacesilent 4 (I only have 3 monitors) the plugin works nice and I can move between workspaces on that monitor sometimes
> 
> What do you mean by this?
> 
> This plugin will create `x` workspaces on each monitor, `x` being defined by `count = x` in the split-monitor-workspaces plugin configuration. In your case you set `x` to 4. This means that each monitor will have 4 workspaces assigned to it. If you call `split-movetoworkspacesilent, 4`, this means you will send the currently focused window to the 4th workspace on the current monitor (silently, meaning you don't activate that workspace, you'll stay on the current workspace).
> 
> The `split-workspace x` dispatcher will activate the `x`th workspace on the current monitor. This has nothing to do with the amount of monitors you have.

yeah, this was working in the way you wrote this, but with this version, if I use this
split-movetoworkspacesilent, 4
I got moved the window to workspace 4 (expected behavior, but in log says Last monitor does not exist,)
If I use
split-movetoworkspacesilent, 2
The window is moved to monitor 2 instead of workspace 2 of current monititor

**Comment by jorgemota** [comment] 2024-07-16 20:59
> > after rebuild do a small test, change to workspace 4, move window to workspace 4, then 1,2,3 and a few tests
> > [hyprland.log](https://github.com/user-attachments/files/16256505/hyprland.log)
> 
> ```
> [INFO] [split-monitor-workspaces] Notifications are enabled
> [INFO] [split-monitor-workspaces] Mapping 4 workspaces to monitors...
> [WARN] [split-monitor-workspaces] Monitor is null
> [WARN] [split-monitor-workspaces] Monitor is null
> [WARN] [split-monitor-workspaces] Monitor is null
> ```
> 
> Something is definitely wrong here: all your monitors are null.
> 
> What's the output of `hyprctl monitors -j`?

[file.txt](https://github.com/user-attachments/files/16256534/file.txt)

**Comment by zjeffer** [comment] 2024-07-16 21:03
> yeah, this was working in the way you wrote this, but with this version, if I use this
split-movetoworkspacesilent, 4
I got moved the window to workspace 4 (expected behavior, but in log says Last monitor does not exist,)
If I use
split-movetoworkspacesilent, 2
The window is moved to monitor 2 instead of workspace 2 of current monititor

Right, this definitely looks like a consequence of the monitors being null

> [file.txt](https://github.com/user-attachments/files/16256534/file.txt)

This looks fine. No clue what is going on here.

**Comment by jorgemota** [comment] 2024-07-16 21:04
> > yeah, this was working in the way you wrote this, but with this version, if I use this
> > split-movetoworkspacesilent, 4
> > I got moved the window to workspace 4 (expected behavior, but in log says Last monitor does not exist,)
> > If I use
> > split-movetoworkspacesilent, 2
> > The window is moved to monitor 2 instead of workspace 2 of current monititor
> 
> Right, this definitely looks like a consequence of the monitors being null
> 
> > [file.txt](https://github.com/user-attachments/files/16256534/file.txt)
> 
> This looks fine. No clue what is going on here.
after changing monitor settings before enable plugin

[hyprland.log](https://github.com/user-attachments/files/16256580/hyprland.log)

**Comment by zjeffer** [comment] 2024-07-16 21:31
I asked for help in the Hyprland discord

**Comment by jorgemota** [comment] 2024-07-17 20:47
Changed in arch linux from hyprland-git to hyprland  package and plugin works again, maybe something with -git version

**Comment by zjeffer** [comment] 2024-07-18 19:43
Vaxry responded saying it might be due to mismatched headers, but I don't understand that because you also tried it with hyprpm which takes care of the headers... Good that you got it to work again with the non-git package.

**Comment by jorgemota** [comment] 2024-07-18 20:37
> Vaxry responded saying it might be due to mismatched headers, but I don't understand that because you also tried it with hyprpm which takes care of the headers... Good that you got it to work again with the non-git package.

I am not sure if this can be the reason, I reinstalled the git version, ran hyprpm update.

:) thanks for your help, I learned a lot

**Closed** 2024-07-20 18:19 UTC
Labels: bug
