### ISSUE TITLE
Headers missing

### ISSUE THREAD

**Issue by LimticRage** [Duckonaut/split-monitor-workspaces#137] opened 2024-11-09 12:19 UTC
I have cpio-2.15-1, cmake-3.30.5-1 and meson-1.4.1-1.
My hyprland v0.44.1.

```
hyprpm add https://github.com/Duckonaut/split-monitor-workspaces
✔ adding a new plugin repository from https://github.com/Duckonaut/split-monitor-workspaces
  MAKE SURE that you trust the authors. DO NOT install random plugins without verifying the code and author.
  Are you sure? [Y/n] yt

 → Cloning https://github.com/Duckonaut/split-monitor-workspaces                                
✔ cloned                                                                                        
✔ found hyprpm manifest                                                                         
✔ parsed manifest, found 1 plugins:                                                             
 → split-monitor-workspaces by Duckonaut version                                                
 → Manifest has 10 pins, checking                                                               
✔ commit pin 7c0cec6e8661facf252b2c974f214b60c4f87466 matched hl, resetting                     
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Verifying headers                   
✖ Headers missing. Please run hyprpm update to fix those.
```

**Comment by zjeffer** [comment] 2024-11-09 12:37
> ✖ Headers missing. Please run hyprpm update to fix those.

Did you try this?

**Comment by LimticRage** [comment] 2024-11-09 13:19
Yeah, I get this

```
┌─[bunny@bunny-pc] - [~] - [sab nov 09, 14:15]
└─[$] <> hyprpm update

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                                                           
✔ cloned                                                                                                                                          
 ━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2 / 5  Checking out sources                                                                  
✖ Could not checkout the running Hyprland commit. If you are on -git, try updating.
You can also try re-running hyprpm update with --no-shallow.
┌─[bunny@bunny-pc] - [~] - [sab nov 09, 14:16]
└─[$] <> hyprpm update --no-shallow

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                                                           
✔ cloned                                                                                                                                          
✔ checked out to running ver                                                                                                                      
! configuring Hyprland                                                                                                                            
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building Hyprland                                                                     
✖ Could not configure the hyprland source, cmake complained:
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for module 'udis86>=1.7.2'
--   Package 'udis86', required by 'virtual:world', not found
-- Found Python3: /usr/bin/python3.12 (found version "3.12.7") found components: Interpreter
Building itab.c/itab.h...
-- udis86 dependency not found, falling back to subproject
-- Found wayland-protocols at 
-- Found wayland-scanner pkgdatadir at //usr/share/wayland
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenGL: /usr/lib64/libOpenGL.so  found components: GLES3
-- Checking for module 'hyprutils>=0.2.1'
--   Package 'hyprutils', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - hyprutils>=0.2.1

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:101 (pkg_check_modules)



This likely means that you are missing the above dependencies or they are out of date.
```

**Comment by LimticRage** [comment] 2024-11-09 13:20
lol... sorry I am git stupid xD

**Comment by zjeffer** [comment] 2024-11-09 15:55
Sorry, thought you closed by accident :laughing:

**Comment by zjeffer** [comment] 2024-11-09 15:56
How did you install Hyprland? Seems like something is very wrong with it...

**Comment by LimticRage** [comment] 2024-11-09 19:12
I am on fedora using the copr (solopasha/hyprland) that other use too. 
https://github.com/JaKooLit/Fedora-Hyprland that is the script i use to install hyprland

**Comment by zjeffer** [comment] 2024-11-09 19:59
I think you should ask for help in that repo or in the hyprwm/Hyprland repo. Either way the issue is not with the plugin, but with hyprpm or your installation of Hyprland. I'm not sure I can be of any help.

**Closed by zjeffer** 2024-11-09 19:59 UTC
Labels: build error
